#include "lwip/opt.h"
#include "lwip/init.h"
#include "lwip/timeouts.h"
#include "lwip/mem.h"
#include "lwip/memp.h"
#include "lwip/pbuf.h"
#include "lwip/netif.h"
#include "lwip/ethip6.h"

/* Core */
#include "lwip/def.h"
#include "lwip/sys.h"
#include "lwip/stats.h"
#include "lwip/inet_chksum.h"
#include "lwip/ip.h"
#include "lwip/ip4.h"
#include "lwip/ip4_addr.h"
#include "lwip/udp.h"
#include "lwip/tcp.h"
#include "lwip/raw.h"
#include "lwip/dhcp.h"
#include "lwip/etharp.h"
#include "lwip/icmp.h"
#include "lwip/timeouts.h"
#include "netif/ethernet.h"

/* Suppress unused warnings */
#define LWIP_UNUSED __attribute__((unused))

/* Include all necessary core .c files */
#include "lwip/src/core/def.c"
#include "lwip/src/core/sys.c"
#include "lwip/src/core/stats.c"
#include "lwip/src/core/mem.c"
#include "lwip/src/core/memp.c"
#include "lwip/src/core/pbuf.c"
#include "lwip/src/core/netif.c"
#include "lwip/src/core/timeouts.c"
#include "lwip/src/core/init.c"
#include "lwip/src/core/inet_chksum.c"
#include "lwip/src/core/ip.c"
#include "lwip/src/core/ipv4/ip4.c"
#include "lwip/src/core/ipv4/ip4_addr.c"
#include "lwip/src/core/ipv4/ip4_frag.c"
#include "lwip/src/core/udp.c"
#include "lwip/src/core/tcp.c"
#include "lwip/src/core/tcp_in.c"
#include "lwip/src/core/tcp_out.c"
#include "lwip/src/core/raw.c"
#include "lwip/src/core/ipv4/icmp.c"
#include "lwip/src/core/ipv4/acd.c"
#include "lwip/src/core/ipv4/dhcp.c"
#include "lwip/src/core/ipv4/etharp.c"
#include "lwip/src/netif/ethernet.c"
